### ISSUE TITLE
我这里安装了扫描不到这个插件，显示mysqlKeyword.py文件的第108行显示错误这个该怎么解决呀

### ISSUE THREAD

**Issue by AnCool-OvO** [jeady5/mysqlKeywords#1]
Failed to import plugin mysqlKeywords: f-string expression part cannot include a backslash (mysqlKeyword.py, line 108) @jeady5

**Comment by fengyingbanbo** [comment]
也是这个错误

**Comment by fengyingbanbo** [comment]
[WARNING][2024-04-17 20:16:27][plugin_manager.py:113] - Failed to import plugin mysqlKeywords: f-string expression part cannot include a backslash (mysqlKeyword.py, line 108)

**Comment by AnCool-OvO** [comment]
> [警告][2024-04-17 20:16:27][plugin_manager.py:113] - 无法导入插件 mysqlKeywords：f 字符串表达式部分不能包含反斜杠（mysqlKeyword.py，第 108 行）


就很难搞我尝试解决这个错误但一直未得到解决，好像是语法不通的原因，不知道是不是我的python版本低的原因还是什么

**Comment by jeady5** [comment]
你们用的哪个版本环境，一块贴出来，好查问题

我现在的版本是python 3.11，正常运行

**Comment by AnCool-OvO** [comment]
> 你们用的哪个版本环境，一块贴出来，好查问题
> 
> 我现在的版本是python 3.11，正常运行

Ubuntu 20.04.6 
python版本是 Python 3.9.5

**Comment by jeady5** [comment]
已兼容低版本的f-string字符串格式 见  [v1.0.6](https://github.com/jeady5/mysqlKeywords/tree/v1.0.6)
